### PR TITLE
Use release catalog images

### PR DESCRIPTION
**Pull request by tim-lo**
Using images from the following CASEs:
- ibm-ai-wmltraining-1.0.0
- ibm-apiconnect-3.0.1
- ibm-appconnect-1.5.0
- ibm-aspera-hsts-operator-1.2.2
- ibm-automation-foundation-core-1.1.0
- ibm-cloud-databases-redis-1.3.0
- ibm-cp-common-services-1.5.0
- ibm-cp-integration-2.3.0
- ibm-datapower-operator-cp4i-1.4.0
- ibm-eventstreams-1.3.1
- ibm-integration-asset-repository-1.3.1
- ibm-integration-demos-operator-1.0.0
- ibm-integration-operations-dashboard-2.3.1
- ibm-integration-platform-navigator-1.3.0
- ibm-mq-1.5.1

Tested non-demo 1-click install on `fermi-carol` (`cp4i1` namespace)

### CODE REVIEW

**Review by laurensks — CHANGES_REQUESTED** [review]
You removed the -p from the create catalog sources but not from deploy-og-sub
and I think if the dash -p is removed I think it will use the older images at least for the deploy-og-sub script

**Comment by tim-lo** [comment]
I've kept the pre-release option since we'd need it to test pre-release images again for future releases; though I've updated both sets of operator versions to the latest now.

**Review by DanRoseus — APPROVED** [review]
Looks good!

**Review by laurensks — APPROVED** [review]
lgtm

**Pull request merged**
