### PR TITLE
Faster storage, slow but safe operator install, fail if OD fails [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by DanRoseus**
# NOTE
## Test in progress, do not merge until test complete!!!

### CODE REVIEW

**Comment by hrizvi1** [comment]
We should fail if the performance storage classes fail to provision.
https://github.com/IBM/cp4i-deployment-samples/blob/c94b3412abf31851985b0e4c6885e82bc81a237b/products/bash/1-click-install.sh#L428

What I am seeing with techzone is that they run out of storage in their account and when 1-click tries to setup storage class they get a soft-layer error but the script continues and then apic and asset repo fall over with storage issue

image

**Comment by DanRoseus** [comment]
> We should fail if the performance storage classes fail to provision.

That's failing when the PVC fails to provision, not the storage classes.

**Comment by hrizvi1** [comment]
```
2022/05/13 19:31:33 Terraform apply | null_resource.script: Still creating... [3h26m51s elapsed]
 2022/05/13 19:31:43 Terraform apply | null_resource.script: Still creating... [3h27m1s elapsed]
 2022/05/13 19:31:53 Terraform apply | null_resource.script: Still creating... [3h27m11s elapsed]
 2022/05/13 19:32:01 Terraform apply | null_resource.script (local-exec): Waiting for APIC install to complete (Attempt 51 of 120). Status: Error
 2022/05/13 19:32:03 Terraform apply | null_resource.script: Still creating... [3h27m21s elapsed]
 2022/05/13 19:32:03 Terraform apply | null_resource.script (local-exec): NAME                                         READY                                                                                                                                                                                                                                                           STATUS   VERSION    RECONCILED VERSION   AGE
 2022/05/13 19:32:03 Terraform apply | null_resource.script (local-exec): apiconnectcluster.apiconnect.ibm.com/ademo   ProvisioningFailed: failed to provision volume with StorageClass "cp4i-block-performance": SoftLayer_Exception_Order_LimitReached_Storage_VolumeCount: Your order will exceed the maximum number of storage volumes allowed. Please contact Sales. (HTTP 500)   Error    10.0.4.0                        159m
 2022/05/13 19:32:03 Terraform apply | 
 2022/05/13 19:32:03 Terraform apply | null_resource.script (local-exec): NAME                                                         READY   STATUS   VERSION    RECONCILED VERSION   AGE
 2022/05/13 19:32:03 Terraform apply | null_resource.script (local-exec): managementcluster.management.apiconnect.ibm.com/ademo-mgmt   0/0     Error    10.0.4.0                        157m
 2022/05/13 19:32:03 Terraform apply | 
 2022/05/13 19:32:03 Terraform apply | null_resource.script (local-exec): NAME                                                                        STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS             AGE
 2022/05/13 19:32:03 Terraform apply | null_resource.script (local-exec): persistentvolumeclaim/ace-dashboard-demo-content                            Bound     pvc-3335c735-a47c-4551-a2e3-1193191f569b   20Gi       RWX            ibmc-file-gold-gid       158m
 2022/05/13 19:32:03 Terraform apply | null_resource.script (local-exec): persistentvolumeclaim/ace-designer-demo-ma-content                          Pending                                                                        ibmc-file-gold-gid       155m
 2022/05/13 19:32:03 Terraform apply | null_resource.script (local-exec): persistentvolumeclaim/ademo-mgmt-33283c90-postgres                          Pending                                                                        cp4i-block-performance   150m
 2022/05/13 19:32:03 Terraform apply | null_resource.script (local-exec): persistentvolumeclaim/ademo-mgmt-33283c90-postgres-pgbr-repo                Pending                                                                        cp4
```

**Comment by DanRoseus** [comment]
@hrizvi1 your log snippet shows a problem waiting for a PVC to bind, not a problem with creating the storage class

**Review by hrizvi1 — APPROVED** [review]
LGTM

**Pull request merged**
