### PR TITLE
Fix sql injection issue for DDD

### PR DESCRIPTION
**Pull request by DanRoseus**
The new code was tested by running the pipeline, which exercises both the POST/GET:
image

### CODE REVIEW

**Comment by DanRoseus** [comment]
This is not obvious from the diffs, but the following classes have been updated to use bind variables:

## GetQuote_SELECT
```java
package com.ibm.demo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import com.ibm.broker.javacompute.MbJavaComputeNode;
import com.ibm.broker.plugin.MbElement;
import com.ibm.broker.plugin.MbException;
import com.ibm.broker.plugin.MbJSON;
import com.ibm.broker.plugin.MbMessage;
import com.ibm.broker.plugin.MbMessageAssembly;
import com.ibm.broker.plugin.MbOutputTerminal;
import com.ibm.broker.plugin.MbUserException;

public class GetQuote_SELECT extends MbJavaComputeNode {

	public void evaluate(MbMessageAssembly inAssembly) throws MbException {
		MbOutputTerminal out = getOutputTerminal("out");
		MbOutputTerminal alt = getOutputTerminal("alternate");

		MbMessage inMessage = inAssembly.getMessage();
		MbMessageAssembly outAssembly = null;
		try {
			// create new message as a copy of the input
			MbMessage outMessage = new MbMessage(inMessage);
			outAssembly = new MbMessageAssembly(inAssembly, outMessage);
			// ----------------------------------------------------------
			// Add user code below			
			MbElement LocalEnv = inAssembly.getLocalEnvironment().getRootElement();			
			MbElement WhereQuoteID = LocalEnv.getFirstElementByPath("/REST/Input/Parameters/QuoteID");
			MbElement WhereName = LocalEnv.getFirstElementByPath("/REST/Input/Parameters/Name");
			MbElement WhereEmail = LocalEnv.getFirstElementByPath("/REST/Input/Parameters/Email");						
			MbElement outputJsonRoot = outMessage.getRootElement().createElementAsLastChild(MbJSON.PARSER_NAME);
			MbElement outputJsonData = outputJsonRoot.createElementAsLastChild(MbJSON.ARRAY,MbJSON.DATA_ELEMENT_NAME, null);
			Connection conn = getJDBCType4Connection("{DefaultPolicies}:PostgresqlPolicy", JDBC_TransactionType.MB_TRANSACTION_AUTO);
			Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
			if (WhereQuoteID!=null) {				
				ResultSet rs = stmt.executeQuery("SELECT * FROM QUOTES WHERE QuoteID="+WhereQuoteID.getValueAsString());
				createResponse(rs, outputJsonData);
			} else if (WhereEmail!=null) {
				// Add LIMIT 5 just in case we end up with 100s or 1000s of table entries!
				ResultSet rs = stmt.executeQuery("SELECT * FROM QUOTES WHERE Email='"+WhereEmail.getValueAsString()+"' LIMIT 5");
				createResponse(rs, outputJsonData);				
			} else if (WhereName!=null)	{	
				// Add LIMIT 5 just in case we end up with 100s or 1000s of table entries!
				ResultSet rs = stmt.executeQuery("SELECT * FROM QUOTES WHERE Name='"+WhereName.getValueAsString()+"' LIMIT 5");
				createResponse(rs, outputJsonData);
			} else {
				outputJsonData.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "Error", "Cannot locate a quote due to not finding one of QuoteID, Email or Name parameter in the request.");
			}
			// End of user code
			// ----------------------------------------------------------
		} catch (MbException e) {
			// Re-throw to allow Broker handling of MbException
			throw e;
		} catch (RuntimeException e) {
			// Re-throw to allow Broker handling of RuntimeException
			throw e;
		} catch (Exception e) {
			// Consider replacing Exception with type(s) thrown by user code
			// Example handling ensures all exceptions are re-thrown to be handled in the flow
			throw new MbUserException(this, "evaluate()", "", "", e.toString(),
					null);
		}
		// The following should only be changed
		// if not propagating message to the 'out' terminal
		out.propagate(outAssembly);

	}

	
	public void createResponse(ResultSet rs, MbElement outputJsonData) throws Exception {	
		while (rs.next()) {					
			MbElement QuoteCurrentArrayItem = outputJsonData.createElementAsLastChild(MbElement.TYPE_NAME, MbJSON.ARRAY_ITEM_NAME, null);					
			QuoteCurrentArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "QuoteID", rs.getString("quoteid"));
			QuoteCurrentArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "Name", rs.getString("name"));
			QuoteCurrentArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "Email", rs.getString("email"));
			QuoteCurrentArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "Address", rs.getString("address"));
			QuoteCurrentArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "USState", rs.getString("usstate"));
			QuoteCurrentArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "LicensePlate", rs.getString("licenseplate"));
			MbElement RepairQuotes = QuoteCurrentArrayItem.createElementAsLastChild(MbJSON.ARRAY, "RepairQuotes", null);
			MbElement RepairQuoteArrayItemAcme = RepairQuotes.createElementAsLastChild(MbElement.TYPE_NAME, MbJSON.ARRAY_ITEM_NAME, null);
			RepairQuoteArrayItemAcme.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "VendorName", "AcmeAutoAccidents");
			RepairQuoteArrayItemAcme.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "CostEstimate", rs.getString("acmecost"));
			RepairQuoteArrayItemAcme.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "EarliestAppointmentDate", rs.getString("acmedate"));
			MbElement RepairQuoteArrayItemBernie = RepairQuotes.createElementAsLastChild(MbElement.TYPE_NAME, MbJSON.ARRAY_ITEM_NAME, null);
			RepairQuoteArrayItemBernie.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "VendorName", "BernieBashedBumpers");
			RepairQuoteArrayItemBernie.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "CostEstimate", rs.getString("berniecost"));
			RepairQuoteArrayItemBernie.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "EarliestAppointmentDate", rs.getString("berniedate"));
			MbElement RepairQuoteArrayItemChris = RepairQuotes.createElementAsLastChild(MbElement.TYPE_NAME, MbJSON.ARRAY_ITEM_NAME, null);
			RepairQuoteArrayItemChris.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "VendorName", "ChrisCrumpledCars");
			RepairQuoteArrayItemChris.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "CostEstimate", rs.getString("chriscost"));
			RepairQuoteArrayItemChris.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "EarliestAppointmentDate", rs.getString("chrisdate"));
			
			}
	}
	
	
	/**
	 * onPreSetupValidation() is called during the construction of the node
	 * to allow the node configuration to be validated.  Updating the node
	 * configuration or connecting to external resources should be avoided.
	 *
	 * @throws MbException
	 */
	@Override
	public void onPreSetupValidation() throws MbException {
	}

	/**
	 * onSetup() is called during the start of the message flow allowing
	 * configuration to be read/cached, and endpoints to be registered.
	 *
	 * Calling getPolicy() within this method to retrieve a policy links this
	 * node to the policy. If the policy is subsequently redeployed the message
	 * flow will be torn down and reinitialized to it's state prior to the policy
	 * redeploy.
	 *
	 * @throws MbException
	 */
	@Override
	public void onSetup() throws MbException {
	}

	/**
	 * onStart() is called as the message flow is started. The thread pool for
	 * the message flow is running when this method is invoked.
	 *
	 * @throws MbException
	 */
	@Override
	public void onStart() throws MbException {
	}

	/**
	 * onStop() is called as the message flow is stopped. 
	 *
	 * The onStop method is called twice as a message flow is stopped. Initially
	 * with a 'wait' value of false and subsequently with a 'wait' value of true.
	 * Blocking operations should be avoided during the initial call. All thread
	 * pools and external connections should be stopped by the completion of the
	 * second call.
	 *
	 * @throws MbException
	 */
	@Override
	public void onStop(boolean wait) throws MbException {
	}

	/**
	 * onTearDown() is called to allow any cached data to be released and any
	 * endpoints to be deregistered.
	 *
	 * @throws MbException
	 */
	@Override
	public void onTearDown() throws MbException {
	}

}
```

## PostQuote_INSERT
```java
package com.ibm.demo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import com.ibm.broker.javacompute.MbJavaComputeNode;
import com.ibm.broker.plugin.MbElement;
import com.ibm.broker.plugin.MbException;
import com.ibm.broker.plugin.MbMessage;
import com.ibm.broker.plugin.MbMessageAssembly;
import com.ibm.broker.plugin.MbOutputTerminal;
import com.ibm.broker.plugin.MbUserException;

public class PostQuote_INSERT extends MbJavaComputeNode {

	public void evaluate(MbMessageAssembly inAssembly) throws MbException {
		MbOutputTerminal out = getOutputTerminal("out");
		MbOutputTerminal alt = getOutputTerminal("alternate");

		MbMessage inMessage = inAssembly.getMessage();
		MbMessageAssembly outAssembly = null;
		try {
			// create new message as a copy of the input
			MbMessage outMessage = new MbMessage(inMessage);
			outAssembly = new MbMessageAssembly(inAssembly, outMessage);
			// ----------------------------------------------------------
			// Add user code below
			
			
			MbElement DataRoot = outMessage.getRootElement().getLastChild().getFirstElementByPath("/JSON/Data");
			// Obtain a java.sql.Connection using a JDBC Type4 datasource
	        // This example uses a Policy of type JDBCProviders called "MyJDBCPolicy" in Policy Project "MyPolicies"  
	        Connection conn = getJDBCType4Connection("{DefaultPolicies}:PostgresqlPolicy", JDBC_TransactionType.MB_TRANSACTION_AUTO);
	        // Example of using the Connection to create a java.sql.Statement 
	        
    		Object name = DataRoot.getFirstElementByPath("Name").getValue();
    		Object email = DataRoot.getFirstElementByPath("EMail").getValue();
    		Object address = DataRoot.getFirstElementByPath("Address").getValue();
    		Object usState = DataRoot.getFirstElementByPath("USState").getValue();
    		Object licensePlate = DataRoot.getFirstElementByPath("LicensePlate").getValue();
    		
    		String sql = "INSERT INTO QUOTES(Name,EMail,Address,USState,LicensePlate) VALUES(?,?,?,?,?) RETURNING *";
	        
	        PreparedStatement pstmt = conn.prepareStatement(sql);
	        pstmt.setObject(1, name);
	        pstmt.setObject(2, email);
	        pstmt.setObject(3, address);
	        pstmt.setObject(4, usState);
	        pstmt.setObject(5, licensePlate);
	        
	        ResultSet rs = pstmt.executeQuery();       
	        rs.next();	        	        
	        DataRoot.createElementAsFirstChild(MbElement.TYPE_NAME, "RequestID", rs.getInt("quoteid")); 	        
	        
			// To test without access to postgresql, you can comment the user code above here and uncomment the next two lines 
			// MbElement DataRoot = outMessage.getRootElement().getLastChild().getFirstElementByPath("/JSON/Data");
	        // DataRoot.createElementAsFirstChild(MbElement.TYPE_NAME, "RequestID", "1");
	        // Also uncomment the marked line 11 lines below here!
	        
	        // Set up the context to carry the HTTP Reply information
	        MbElement Destination = outAssembly.getGlobalEnvironment().getRootElement().createElementAsLastChild(MbElement.TYPE_NAME, "Destination", null);
	        MbElement GroupScatter = Destination.createElementAsLastChild(MbElement.TYPE_NAME, "GroupScatter", null);
	        MbElement Context = GroupScatter.createElementAsLastChild(MbElement.TYPE_NAME, "Context", null);
	        MbElement HTTP = Context.createElementAsLastChild(MbElement.TYPE_NAME, "HTTP", null);
	        HTTP.createElementAsLastChild(MbElement.TYPE_NAME, "RequestIdentifier",	        		
	        		outAssembly.getLocalEnvironment().getRootElement().getFirstElementByPath("/Destination/HTTP/RequestIdentifier").getValue());	        
	        Context.createElementAsLastChild(MbElement.TYPE_NAME, "QuoteID", rs.getInt("quoteid"));

	        // To test without access to postgresql, uncomment this next line
	        // Context.createElementAsLastChild(MbElement.TYPE_NAME, "QuoteID", "1");
	        Context.createElementAsLastChild(MbElement.TYPE_NAME, "Name", DataRoot.getFirstElementByPath("Name").getValue());
	        Context.createElementAsLastChild(MbElement.TYPE_NAME, "EMail", DataRoot.getFirstElementByPath("EMail").getValue());	                
	        Context.createElementAsLastChild(MbElement.TYPE_NAME, "Address", DataRoot.getFirstElementByPath("Address").getValue());
	        Context.createElementAsLastChild(MbElement.TYPE_NAME, "USState", DataRoot.getFirstElementByPath("USState").getValue());
	        Context.createElementAsLastChild(MbElement.TYPE_NAME, "LicensePlate", DataRoot.getFirstElementByPath("LicensePlate").getValue());
	        
	        // Remove fields which don't get sent to the back ends: Name, EMail, Address and USState
	        DataRoot.getFirstElementByPath("Name").delete();
	        DataRoot.getFirstElementByPath("EMail").delete();
	        DataRoot.getFirstElementByPath("Address").delete();
	        DataRoot.getFirstElementByPath("USState").delete();	        
	        
			// End of user code
			// ----------------------------------------------------------
		} catch (MbException e) {
			// Re-throw to allow Broker handling of MbException
			throw e;
		} catch (RuntimeException e) {
			// Re-throw to allow Broker handling of RuntimeException
			throw e;
		} catch (Exception e) {
			// Consider replacing Exception with type(s) thrown by user code
			// Example handling ensures all exceptions are re-thrown to be handled in the flow
			throw new MbUserException(this, "evaluate()", "", "", e.toString(),
					null);
		}
		// The following should only be changed
		// if not propagating message to the 'out' terminal
		out.propagate(outAssembly);

	}

	/**
	 * onPreSetupValidation() is called during the construction of the node
	 * to allow the node configuration to be validated.  Updating the node
	 * configuration or connecting to external resources should be avoided.
	 *
	 * @throws MbException
	 */
	@Override
	public void onPreSetupValidation() throws MbException {
	}

	/**
	 * onSetup() is called during the start of the message flow allowing
	 * configuration to be read/cached, and endpoints to be registered.
	 *
	 * Calling getPolicy() within this method to retrieve a policy links this
	 * node to the policy. If the policy is subsequently redeployed the message
	 * flow will be torn down and reinitialized to it's state prior to the policy
	 * redeploy.
	 *
	 * @throws MbException
	 */
	@Override
	public void onSetup() throws MbException {
	}

	/**
	 * onStart() is called as the message flow is started. The thread pool for
	 * the message flow is running when this method is invoked.
	 *
	 * @throws MbException
	 */
	@Override
	public void onStart() throws MbException {
	}

	/**
	 * onStop() is called as the message flow is stopped. 
	 *
	 * The onStop method is called twice as a message flow is stopped. Initially
	 * with a 'wait' value of false and subsequently with a 'wait' value of true.
	 * Blocking operations should be avoided during the initial call. All thread
	 * pools and external connections should be stopped by the completion of the
	 * second call.
	 *
	 * @throws MbException
	 */
	@Override
	public void onStop(boolean wait) throws MbException {
	}

	/**
	 * onTearDown() is called to allow any cached data to be released and any
	 * endpoints to be deregistered.
	 *
	 * @throws MbException
	 */
	@Override
	public void onTearDown() throws MbException {
	}

}
```

## PostQuote_UPDATE
```java
package com.ibm.demo;

import java.sql.Connection;
import java.sql.PreparedStatement;

import com.ibm.broker.javacompute.MbJavaComputeNode;
import com.ibm.broker.plugin.MbElement;
import com.ibm.broker.plugin.MbException;
import com.ibm.broker.plugin.MbJSON;
import com.ibm.broker.plugin.MbMessage;
import com.ibm.broker.plugin.MbMessageAssembly;
import com.ibm.broker.plugin.MbOutputTerminal;
import com.ibm.broker.plugin.MbUserException;

public class PostQuote_UPDATE extends MbJavaComputeNode {
	static private Integer toInteger(Object value) {
		if(value == null) return null;
    	try {
    		return Integer.valueOf(value.toString());
    	} catch (NumberFormatException e) {
    		return null;
    	}
	}
	
	public void evaluate(MbMessageAssembly inAssembly) throws MbException {
		MbOutputTerminal out = getOutputTerminal("out");
		MbOutputTerminal alt = getOutputTerminal("alternate");

		MbMessage inMessage = inAssembly.getMessage();

		// create new empty message
		MbMessage outMessage = new MbMessage();
		MbMessageAssembly outAssembly = new MbMessageAssembly(inAssembly,
				outMessage);

		try {
			// optionally copy message headers
			copyMessageHeaders(inMessage, outMessage);
			// ----------------------------------------------------------
			// Add user code below
			MbElement outRoot = outMessage.getRootElement();
			MbElement outJsonRoot = outRoot.createElementAsLastChild(MbJSON.PARSER_NAME);
			MbElement outJsonData = outJsonRoot.createElementAsLastChild(MbElement.TYPE_NAME, MbJSON.DATA_ELEMENT_NAME, null);
			outJsonData.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "QuoteID", 
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Context/QuoteID").getValue());
			outJsonData.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "Name",
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Context/Name").getValue());
			outJsonData.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "EMail", 
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Context/EMail").getValue());
			outJsonData.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "Address", 
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Context/Address").getValue());
			outJsonData.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "USState", 
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Context/USState").getValue());
			outJsonData.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "LicensePlate", 
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Context/LicensePlate").getValue());						
			String backEndVersions = 
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Accident/Reply/Root/JSON/Data/Version").getValue() + "," +
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Bumper/Reply/Root/JSON/Data/Version").getValue() + "," +
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Crumpled/Reply/Root/JSON/Data/Version").getValue();					
			outJsonData.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "Versions", backEndVersions);					
			MbElement RepairQuotes = outJsonData.createElementAsLastChild(MbJSON.ARRAY, "RepairQuotes", null);
			MbElement FirstArrayItem = RepairQuotes.createElementAsLastChild(MbElement.TYPE_NAME, MbJSON.ARRAY_ITEM_NAME, null);
			MbElement SecondArrayItem = RepairQuotes.createElementAsLastChild(MbElement.TYPE_NAME, MbJSON.ARRAY_ITEM_NAME, null);
			MbElement ThirdArrayItem = RepairQuotes.createElementAsLastChild(MbElement.TYPE_NAME, MbJSON.ARRAY_ITEM_NAME, null);			
			FirstArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "VendorName", "AcmeAutoAccidents");
			FirstArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "CostEstimate",
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Accident/Reply/Root/JSON/Data/EstimatedCost").getValue());
			FirstArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "EarliestAppointmentDate",			
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Accident/Reply/Root/JSON/Data/EarliestStartDate").getValue());
			SecondArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "VendorName", "BernieBashedBumpers");
			SecondArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "CostEstimate", 
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Bumper/Reply/Root/JSON/Data/EstimatedCost").getValue());										
			SecondArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "EarliestAppointmentDate",
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Bumper/Reply/Root/JSON/Data/EarliestStartDate").getValue());					
			ThirdArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "VendorName", "ChrisCrumpledCars");
			ThirdArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "CostEstimate",
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Crumpled/Reply/Root/JSON/Data/EstimatedCost").getValue());
			ThirdArrayItem.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "EarliestAppointmentDate",
				inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Crumpled/Reply/Root/JSON/Data/EarliestStartDate").getValue());			
			// Set HTTP info
			MbElement LocalEnv = outAssembly.getLocalEnvironment().getRootElement();
			MbElement Destination = LocalEnv.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "Destination", null);
			MbElement HTTP = Destination.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "HTTP", null);
			HTTP.createElementAsLastChild(MbElement.TYPE_NAME_VALUE, "RequestIdentifier", inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Context/HTTP/RequestIdentifier").getValue());

			// To test without access to postgresql, you can comment out the user code below here ...
			
			// Update quote information in the Postgresql database using the reply data ...			
	        Connection conn = getJDBCType4Connection("{DefaultPolicies}:PostgresqlPolicy", JDBC_TransactionType.MB_TRANSACTION_AUTO);
	        
	        Object acmecost = toInteger(inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Accident/Reply/Root/JSON/Data/EstimatedCost").getValue());
	        Object acmedate = inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Accident/Reply/Root/JSON/Data/EarliestStartDate").getValue();
	        Object berniecost = toInteger(inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Bumper/Reply/Root/JSON/Data/EstimatedCost").getValue()); 
    		Object berniedate = inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Bumper/Reply/Root/JSON/Data/EarliestStartDate").getValue();
    		Object chriscost = toInteger(inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Crumpled/Reply/Root/JSON/Data/EstimatedCost").getValue());
			Object chrisdate = inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Replies/Crumpled/Reply/Root/JSON/Data/EarliestStartDate").getValue();
			Object quoteid = inAssembly.getMessage().getRootElement().getFirstElementByPath("ComIbmGroupCompleteNode/Group/Context/QuoteID").getValue();

			String sql = "UPDATE quotes SET acmecost=?, acmedate=?::date, berniecost=?, berniedate=?::date, chriscost=?, chrisdate=?::date WHERE quoteid=?";

	        PreparedStatement pstmt = conn.prepareStatement(sql);
	        pstmt.setObject(1, acmecost);
	        pstmt.setObject(2, acmedate);
	        pstmt.setObject(3, berniecost);
	        pstmt.setObject(4, berniedate);
	        pstmt.setObject(5, chriscost);
	        pstmt.setObject(6, chrisdate);
	        pstmt.setObject(7, quoteid);
	        	        
	        pstmt.executeUpdate();

	        // End of user code
			// ----------------------------------------------------------
		} catch (MbException e) {
			// Re-throw to allow Broker handling of MbException
			throw e;
		} catch (RuntimeException e) {
			// Re-throw to allow Broker handling of RuntimeException
			throw e;
		} catch (Exception e) {
			// Consider replacing Exception with type(s) thrown by user code
			// Example handling ensures all exceptions are re-thrown to be handled in the flow
			throw new MbUserException(this, "evaluate()", "", "", e.toString(),
					null);
		}
		// The following should only be changed
		// if not propagating message to the 'out' terminal
		out.propagate(outAssembly);
	}

	public void copyMessageHeaders(MbMessage inMessage, MbMessage outMessage)
			throws MbException {
		MbElement outRoot = outMessage.getRootElement();

		// iterate though the headers starting with the first child of the root
		// element, stopping before the last child (body)
		MbElement header = inMessage.getRootElement().getFirstChild();
		while (header != null && header.getNextSibling() != null) {
			// copy the header and add it to the out message
			MbElement newHeader = outRoot.createElementAsLastChild(header
					.getParserClassName());
			newHeader.setName(header.getName());
			newHeader.copyElementTree(header);
			// move along to next header
			header = header.getNextSibling();
		}
	}

	/**
	 * onPreSetupValidation() is called during the construction of the node
	 * to allow the node configuration to be validated.  Updating the node
	 * configuration or connecting to external resources should be avoided.
	 *
	 * @throws MbException
	 */
	@Override
	public void onPreSetupValidation() throws MbException {
	}

	/**
	 * onSetup() is called during the start of the message flow allowing
	 * configuration to be read/cached, and endpoints to be registered.
	 *
	 * Calling getPolicy() within this method to retrieve a policy links this
	 * node to the policy. If the policy is subsequently redeployed the message
	 * flow will be torn down and reinitialized to it's state prior to the policy
	 * redeploy.
	 *
	 * @throws MbException
	 */
	@Override
	public void onSetup() throws MbException {
	}

	/**
	 * onStart() is called as the message flow is started. The thread pool for
	 * the message flow is running when this method is invoked.
	 *
	 * @throws MbException
	 */
	@Override
	public void onStart() throws MbException {
	}

	/**
	 * onStop() is called as the message flow is stopped. 
	 *
	 * The onStop method is called twice as a message flow is stopped. Initially
	 * with a 'wait' value of false and subsequently with a 'wait' value of true.
	 * Blocking operations should be avoided during the initial call. All thread
	 * pools and external connections should be stopped by the completion of the
	 * second call.
	 *
	 * @throws MbException
	 */
	@Override
	public void onStop(boolean wait) throws MbException {
	}

	/**
	 * onTearDown() is called to allow any cached data to be released and any
	 * endpoints to be deregistered.
	 *
	 * @throws MbException
	 */
	@Override
	public void onTearDown() throws MbException {
	}

}
```

**Comment by hrizvi1** [comment]
Just wondering if instead of throws, can we have print of stack trace?

**Comment by DanRoseus** [comment]
> Just wondering if instead of throws, can we have print of stack trace?

When the exception is re-thrown ACE catches it and outputs the exception info. I.e. during development I had:
```
2020-10-21 10:25:52.483312: Exception condition detected on input node 'gen.DrivewayDentDeletion.postQuote (Implementation).Group Complete'. 
2020-10-21 10:25:52.483420: Error detected whilst processing a message in node 'gen.DrivewayDentDeletion.postQuote (Implementation).UPDATE'. 
2020-10-21 10:25:52.483476: The method 'evaluate' in Java node 'postQuote (Implementation).UPDATE' has thrown the following exception: <com.ibm.broker.plugin.MbUserException class:com.ibm.demo.PostQuote_UPDATE method:evaluate() source: key: message: Unable to resolve message: Source: Key:  >. 
2020-10-21 10:25:52.483524: Java exception: 'com.ibm.broker.plugin.MbUserException'; thrown from class name: 'com.ibm.demo.PostQuote_UPDATE', method name: 'evaluate()', file: 'PostQuote_UPDATE.java', line: '123'; trace text: 'org.postgresql.util.PSQLException: No results were returned by the query.';  resource bundle: ''; key: ''; inserts(optional): '{8}', '{9}', '{10}', '{11}', '{12}', '{13}', '{14}', '{15}', '{16}', '{17}' 
```
I think this is sufficient for debugging, and I didn't see the problems we saw with EEI, MQ carried on working when the exception was thrown.

**Comment by hrizvi1** [comment]
LGtM

**Review by hrizvi1 — APPROVED** [review]
LGTM

**Pull request merged**
