### PR TITLE
Add psql release script

### PR DESCRIPTION
**Pull request by tim-lo**

### CODE REVIEW

**Comment by hrizvi1** [comment]
Is there a PR for it in Case repo?

**Comment by DanRoseus** [comment]
> Is there a PR for it in Case repo?

Yes, I'm reviewing that now. This needs merging before the CASE PR

**Comment by hrizvi1** [comment]
just linking it: https://github.ibm.com/cp4i/cloudpak-for-integration-case/pull/211

**Comment by DanRoseus** [comment]
> just linking it: https://github.ibm.com/cp4i/cloudpak-for-integration-case/pull/211

Probably best to link from private to public rather than public to private, no one outside our group can see the private stuff!

**Pull request merged**
